<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: kadleto2
 * Date: Wed, 24 Jun 2009 18:57:27 +0200
 */

$conf['title'] = '--NI-PON-- --COURSE-NAME--';
$conf['license'] = '';
$conf['rss_linkto'] = 'page';
$conf['plugin']['translation']['translations'] = 'en';
$conf['plugin']['translation']['translateui'] = 1;
$conf['plugin']['gallery']['options'] = 'cache,lightbox,showname,showtitle';
$conf['plugin']['blog']['excluded_pages'] = '!:start$!';
$conf['plugin']['indexmenu']['skip_index'] = '/^[\\\\\\/:]*(sidebar|funding|playground|en|wiki)/';
$conf['plugin']['indexmenu']['skip_file'] = '/(sidebar|start|funding)/';