#!/bin/bash



#get the width of the shell windows - couldnt use tput -> because it gets its value from stdin
width=$(tput cols);
height=$(tput lines);

pocet_znaku=$(( $width / (250 /$height) ));


sed  -e "s/\([^[:space:]].\{$pocet_znaku\}\)\(.*\)\(.\{$pocet_znaku\}\)$/\1...\3/g" 

